### PR TITLE
Address ES6 failling tests

### PR DESCRIPTION
**Pull request by paOol**
This is the first file of the ES6 refactor.

- passes ESLint
- does not pass testing

Please take a look at the changes themselves to see if the ES6 version is correct. There are two lines that may be an issue (commented with 'possible error'). the rest is just style/format changes. 

Also the testing issue may be a result of changing the old function into a class and Classes must use 'new class()' and the test files do not reflect that.

### CODE REVIEW

**Comment by paOol** [comment]
When changing a line in the test/publickey.js file from

`var Address = bch.Address;` to `var Address = new bch.address();` , I get a different error.


```
                                     4m ⚑  
▶ npm run test

> bitcoincashflow@0.1.11 test /home/paool/web/BitcoinSource
> npm run test:node


> bitcoincashflow@0.1.11 test:node /home/paool/web/BitcoinSource
> nyc --reporter=html --reporter=text mocha


/home/paool/web/BitcoinSource/src/util/preconditions.js:1
(function (exports, require, module, __filename, __dirname) { var cov_sxeyfzh36=function(){var path='/home/paool/web/BitcoinSource/src/util/preconditions.js',hash='925614b405586e5faa5855d2ea1661b3a1ee2c28',Function=function(){}.constructor,global=new Function('return this')(),gcv='__coverage__',coverageData={path:'/home/paool/web/BitcoinSource/src/util/preconditions.js',statementMap:{'0':{start:{line:1,column:10},end:{line:1,column:27}},'1':{start:{line:2,column:15},end:{line:2,column:32}},'2':{start:{line:3,column:15},end:{line:3,column:35}},'3':{start:{line:5,column:0},end:{line:30,column:2}},'4':{start:{line:7,column:4},end:{line:9,column:5}},'5':{start:{line:8,column:6},end:{line:8,column:45}},'6':{start:{line:12,column:4},end:{line:14,column:5}},'7':{start:{line:13,column:6},end:{line:13,column:72}},'8':{start:{line:17,column:4},end:{line:17,column:52}},'9':{start:{line:18,column:4},end:{line:28,column:5}},'10':{start:{line:19,column:6},end:{lin
Invalid Argument: First argument is required, please include address data. Documentation: http://bitcore.io/guide/address.html
Error
    at new NodeError (/home/paool/web/BitcoinSource/src/errors/index.js:1:5481)
    at Object.checkArgument (/home/paool/web/BitcoinSource/src/util/preconditions.js:1:3828)
    at new Address (/home/paool/web/BitcoinSource/src/address.js:36:70)
    at Object.<anonymous> (/home/paool/web/BitcoinSource/test/publickey.js:11:15)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/home/paool/web/BitcoinSource/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/paool/web/BitcoinSource/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/paool/web/BitcoinSource/node_modules/nyc/node_modules/append-transform/index.js:62:4)

```

**Comment by lotusbaba** [comment]
Hi there,

Has this change passed `npm run test` on your local branch?

Regards,
Bhaskar.

**Comment by paOol** [comment]
No, that is the issue. 
The class change is not compatible with the existing test files.

I need some help figuring out why or what to change to pass the test with the ES6 refactor before moving on.

**Comment by ClemensLey** [comment]
I think it one thing that would make it easier to figure out what is going here would be to try to keep the edited file as similar to the original file as possible. We'll get a simpler diff if we make sure that we do not change the order of methods etc unless we need to. A simple diff will help us make sure that we are not changing the behavior of the class. Maybe that way we can spot the bug that makes the test fail.

**Comment by lotusbaba** [comment]
Maybe this is the problem -

I see the following error - Address.fromString is not a function

This is a TypeError and is checked in file dist/bitcoincash-0.1.10.min.js

Since after the change this is not a function anymore but a method within
the class it is throwing an error.

What do you think?

Bhaskar.

**Comment by paOol** [comment]
```
Since after the change this is not a function anymore but a method within
the class it is throwing an error.
```
I agree, but I don't see a solution outside of changing some stuff inside of the test files.

**Comment by ClemensLey** [comment]
Great work paOol!

**Comment by lotusbaba** [comment]
@ClemensLey @paOol was looking at the "fixed unit tests" commit 7fb6eaa from above but couldn't tell what was fixed in the tests from the diff. Help me understand pls?

**Comment by lotusbaba** [comment]
OK went through it a bit more and it seems that one of the things that fixed tests was declaring the class methods as static. Seems that designates them as function expressions which is close to a function but not class methods and so passes. Am I right?

**Comment by paOol** [comment]
Yes, if you check out my other PR https://github.com/BitcoinDB/BitcoinSource/pull/98 it's a bit easier to isolate the changes. 

Basically the linter will catch most of the problems and warn you about "this" to be expected. Those can be resolved by adding `static` . 

Also some lines in the test files will require `new` to instantiate in order to work.

**Comment by lotusbaba** [comment]
Got it.

Well this also probably means that, none of the Addtess objects declared in
other files is calling the methods directly.

Bhaskar.

**Pull request merged**
